#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
	exit('O utilitario mf nao pode ser acessado diretamente' . PHP_EOL);
}

$axis = dirname(__DIR__, 1) . DIRECTORY_SEPARATOR . 'axis.php';

if (!is_file($axis)) {
	exit('Axis indisponível.' . PHP_EOL);
	return;
}

